from .bases import Grime2TestBase
from ..enums import EnumItem

class TestOptionItemMoldVanilla(Grime2TestBase):
    options = {"progressiveitemmolds": 0}
    def test_item_mold_vanilla(self) -> None:
        """Test Value - False"""
        item_names = [i.name for i in self.multiworld.get_items()]
        print("False:", item_names)
        self.assertTrue(EnumItem.IM_PROG_CELEBRATION_BELL.value not in item_names)
        self.assertTrue(EnumItem.IM_PROG_CHAIN_JAVELIN.value not in item_names)
        self.assertTrue(EnumItem.IM_PROG_CHARGING_JAVELIN.value not in item_names)
        self.assertTrue(EnumItem.IM_PROG_DEFENSE_SIGILS.value not in item_names)
        self.assertTrue(EnumItem.IM_PROG_DRIED_ALVEOLI.value not in item_names)
        self.assertTrue(EnumItem.IM_PROG_EMBEDDING_NAIL.value not in item_names)
        self.assertTrue(EnumItem.IM_PROG_HOMING_DROPLET.value not in item_names)
        self.assertTrue(EnumItem.IM_PROG_KNOCKBACK_WEAVE.value not in item_names)
        self.assertTrue(EnumItem.IM_PROG_LUMP_OF_HANDS.value not in item_names)
        self.assertTrue(EnumItem.IM_PROG_OVERGROWN_BLOB.value not in item_names)
        self.assertTrue(EnumItem.IM_PROG_PRIMING_SPEAR.value not in item_names)
        self.assertTrue(EnumItem.IM_PROG_REINFORCING_WEAVE.value not in item_names)
        self.assertTrue(EnumItem.IM_PROG_SCATTER_STONE.value not in item_names)
        self.assertTrue(EnumItem.IM_PROG_SHARPENING_WEAVE.value not in item_names)
        self.assertTrue(EnumItem.IM_PROG_SIGIL_BARRIER.value not in item_names)
        self.assertTrue(EnumItem.IM_PROG_SMASHING_BLOCK.value not in item_names)
        self.assertTrue(EnumItem.IM_PROG_SMIDGE_OF_PAINT.value not in item_names)
        self.assertTrue(EnumItem.IM_PROG_SPIKE_BALL.value not in item_names)
        self.assertTrue(EnumItem.IM_PROG_TRIGGER_BOMB.value not in item_names)
        self.assertTrue(EnumItem.IM_PROG_VOLATILE_VASE.value not in item_names)
        
        self.assertTrue(EnumItem.IM_CELEBRATION_BELL.value in item_names)
        self.assertTrue(EnumItem.IM_CHAIN_JAVELIN.value in item_names)
        self.assertTrue(EnumItem.IM_CHARGING_JAVELIN.value in item_names)
        self.assertTrue(EnumItem.IM_DEFENSE_SIGILS.value in item_names)
        self.assertTrue(EnumItem.IM_DRIED_ALVEOLI.value in item_names)
        self.assertTrue(EnumItem.IM_EMBEDDING_NAIL.value in item_names)
        self.assertTrue(EnumItem.IM_HOMING_DROPLET.value in item_names)
        self.assertTrue(EnumItem.IM_KNOCKBACK_WEAVE.value in item_names)
        self.assertTrue(EnumItem.IM_LUMP_OF_HANDS.value in item_names)
        self.assertTrue(EnumItem.IM_OVERGROWN_BLOB.value in item_names)
        self.assertTrue(EnumItem.IM_PRIMING_SPEAR.value in item_names)
        self.assertTrue(EnumItem.IM_REINFORCING_WEAVE.value in item_names)
        self.assertTrue(EnumItem.IM_SCATTER_STONE.value in item_names)
        self.assertTrue(EnumItem.IM_SHARPENING_WEAVE.value in item_names)
        self.assertTrue(EnumItem.IM_SIGIL_BARRIER.value in item_names)
        self.assertTrue(EnumItem.IM_SMASHING_BLOCK.value in item_names)
        self.assertTrue(EnumItem.IM_SMIDGE_OF_PAINT.value in item_names)
        self.assertTrue(EnumItem.IM_SPIKE_BALL.value in item_names)
        self.assertTrue(EnumItem.IM_TRIGGER_BOMB.value in item_names)
        self.assertTrue(EnumItem.IM_VOLATILE_VASE.value in item_names)
        
        self.assertTrue(item_names.count(EnumItem.IM_CELEBRATION_BELL.value) == 10)
        self.assertTrue(item_names.count(EnumItem.IM_CHAIN_JAVELIN.value) == 10)
        self.assertTrue(item_names.count(EnumItem.IM_CHARGING_JAVELIN.value) == 8)
        self.assertTrue(item_names.count(EnumItem.IM_DEFENSE_SIGILS.value) == 6)
        self.assertTrue(item_names.count(EnumItem.IM_DRIED_ALVEOLI.value) == 14)
        self.assertTrue(item_names.count(EnumItem.IM_EMBEDDING_NAIL.value) == 8)
        self.assertTrue(item_names.count(EnumItem.IM_HOMING_DROPLET.value) == 12)
        self.assertTrue(item_names.count(EnumItem.IM_KNOCKBACK_WEAVE.value) == 10)
        self.assertTrue(item_names.count(EnumItem.IM_LUMP_OF_HANDS.value) == 8)
        self.assertTrue(item_names.count(EnumItem.IM_OVERGROWN_BLOB.value) == 8)
        self.assertTrue(item_names.count(EnumItem.IM_PRIMING_SPEAR.value) == 12)
        self.assertTrue(item_names.count(EnumItem.IM_REINFORCING_WEAVE.value) == 7)
        self.assertTrue(item_names.count(EnumItem.IM_SCATTER_STONE.value) == 8)
        self.assertTrue(item_names.count(EnumItem.IM_SHARPENING_WEAVE.value) == 8)
        self.assertTrue(item_names.count(EnumItem.IM_SIGIL_BARRIER.value) == 7)
        self.assertTrue(item_names.count(EnumItem.IM_SMASHING_BLOCK.value) == 8)
        self.assertTrue(item_names.count(EnumItem.IM_SMIDGE_OF_PAINT.value) == 8)
        self.assertTrue(item_names.count(EnumItem.IM_SPIKE_BALL.value) == 8)
        self.assertTrue(item_names.count(EnumItem.IM_TRIGGER_BOMB.value) == 12)
        self.assertTrue(item_names.count(EnumItem.IM_VOLATILE_VASE.value) == 8)

class TestOptionItemMoldProg(Grime2TestBase):
    options = {"progressiveitemmolds": 1}
    def test_item_mold_prog(self) -> None:
        """Test Value - True"""
        item_names = [i.name for i in self.multiworld.get_items()]
        print("True:", item_names)
        self.assertTrue(EnumItem.IM_PROG_CELEBRATION_BELL.value in item_names)
        self.assertTrue(EnumItem.IM_PROG_CHAIN_JAVELIN.value in item_names)
        self.assertTrue(EnumItem.IM_PROG_CHARGING_JAVELIN.value in item_names)
        self.assertTrue(EnumItem.IM_PROG_DEFENSE_SIGILS.value in item_names)
        self.assertTrue(EnumItem.IM_PROG_DRIED_ALVEOLI.value in item_names)
        self.assertTrue(EnumItem.IM_PROG_EMBEDDING_NAIL.value in item_names)
        self.assertTrue(EnumItem.IM_PROG_HOMING_DROPLET.value in item_names)
        self.assertTrue(EnumItem.IM_PROG_KNOCKBACK_WEAVE.value in item_names)
        self.assertTrue(EnumItem.IM_PROG_LUMP_OF_HANDS.value in item_names)
        self.assertTrue(EnumItem.IM_PROG_OVERGROWN_BLOB.value in item_names)
        self.assertTrue(EnumItem.IM_PROG_PRIMING_SPEAR.value in item_names)
        self.assertTrue(EnumItem.IM_PROG_REINFORCING_WEAVE.value in item_names)
        self.assertTrue(EnumItem.IM_PROG_SCATTER_STONE.value in item_names)
        self.assertTrue(EnumItem.IM_PROG_SHARPENING_WEAVE.value in item_names)
        self.assertTrue(EnumItem.IM_PROG_SIGIL_BARRIER.value in item_names)
        self.assertTrue(EnumItem.IM_PROG_SMASHING_BLOCK.value in item_names)
        self.assertTrue(EnumItem.IM_PROG_SMIDGE_OF_PAINT.value in item_names)
        self.assertTrue(EnumItem.IM_PROG_SPIKE_BALL.value in item_names)
        self.assertTrue(EnumItem.IM_PROG_TRIGGER_BOMB.value in item_names)
        self.assertTrue(EnumItem.IM_PROG_VOLATILE_VASE.value in item_names)
        
        self.assertTrue(EnumItem.IM_CELEBRATION_BELL.value not in item_names)
        self.assertTrue(EnumItem.IM_CHAIN_JAVELIN.value not in item_names)
        self.assertTrue(EnumItem.IM_CHARGING_JAVELIN.value not in item_names)
        self.assertTrue(EnumItem.IM_DEFENSE_SIGILS.value not in item_names)
        self.assertTrue(EnumItem.IM_DRIED_ALVEOLI.value not in item_names)
        self.assertTrue(EnumItem.IM_EMBEDDING_NAIL.value not in item_names)
        self.assertTrue(EnumItem.IM_HOMING_DROPLET.value not in item_names)
        self.assertTrue(EnumItem.IM_KNOCKBACK_WEAVE.value not in item_names)
        self.assertTrue(EnumItem.IM_LUMP_OF_HANDS.value not in item_names)
        self.assertTrue(EnumItem.IM_OVERGROWN_BLOB.value not in item_names)
        self.assertTrue(EnumItem.IM_PRIMING_SPEAR.value not in item_names)
        self.assertTrue(EnumItem.IM_REINFORCING_WEAVE.value not in item_names)
        self.assertTrue(EnumItem.IM_SCATTER_STONE.value not in item_names)
        self.assertTrue(EnumItem.IM_SHARPENING_WEAVE.value not in item_names)
        self.assertTrue(EnumItem.IM_SIGIL_BARRIER.value not in item_names)
        self.assertTrue(EnumItem.IM_SMASHING_BLOCK.value not in item_names)
        self.assertTrue(EnumItem.IM_SMIDGE_OF_PAINT.value not in item_names)
        self.assertTrue(EnumItem.IM_SPIKE_BALL.value not in item_names)
        self.assertTrue(EnumItem.IM_TRIGGER_BOMB.value not in item_names)
        self.assertTrue(EnumItem.IM_VOLATILE_VASE.value not in item_names)
        
        self.assertTrue(item_names.count(EnumItem.IM_PROG_CELEBRATION_BELL.value) == 3)
        self.assertTrue(item_names.count(EnumItem.IM_PROG_CHAIN_JAVELIN.value) == 3)
        self.assertTrue(item_names.count(EnumItem.IM_PROG_CHARGING_JAVELIN.value) == 3)
        self.assertTrue(item_names.count(EnumItem.IM_PROG_DEFENSE_SIGILS.value) == 3)
        self.assertTrue(item_names.count(EnumItem.IM_PROG_DRIED_ALVEOLI.value) == 3)
        self.assertTrue(item_names.count(EnumItem.IM_PROG_EMBEDDING_NAIL.value) == 3)
        self.assertTrue(item_names.count(EnumItem.IM_PROG_HOMING_DROPLET.value) == 3)
        self.assertTrue(item_names.count(EnumItem.IM_PROG_KNOCKBACK_WEAVE.value) == 3)
        self.assertTrue(item_names.count(EnumItem.IM_PROG_LUMP_OF_HANDS.value) == 3)
        self.assertTrue(item_names.count(EnumItem.IM_PROG_OVERGROWN_BLOB.value) == 3)
        self.assertTrue(item_names.count(EnumItem.IM_PROG_PRIMING_SPEAR.value) == 3)
        self.assertTrue(item_names.count(EnumItem.IM_PROG_REINFORCING_WEAVE.value) == 3)
        self.assertTrue(item_names.count(EnumItem.IM_PROG_SCATTER_STONE.value) == 3)
        self.assertTrue(item_names.count(EnumItem.IM_PROG_SHARPENING_WEAVE.value) == 3)
        self.assertTrue(item_names.count(EnumItem.IM_PROG_SIGIL_BARRIER.value) == 3)
        self.assertTrue(item_names.count(EnumItem.IM_PROG_SMASHING_BLOCK.value) == 3)
        self.assertTrue(item_names.count(EnumItem.IM_PROG_SMIDGE_OF_PAINT.value) == 3)
        self.assertTrue(item_names.count(EnumItem.IM_PROG_SPIKE_BALL.value) == 3)
        self.assertTrue(item_names.count(EnumItem.IM_PROG_TRIGGER_BOMB.value) == 3)
        self.assertTrue(item_names.count(EnumItem.IM_PROG_VOLATILE_VASE.value) == 3)
