from enum import StrEnum

class EnumRegions(StrEnum):
    """List of all Temple of Hands enums"""
    TEMPLE_OF_HANDS_BIRTHPLACE_LOWER = "Temple of Hands-Birthplace Lower"
    TEMPLE_OF_HANDS_BIRTHPLACE_UPPER = "Temple of Hands-Birthplace Upper"
    TEMPLE_OF_HANDS_DRIED_PAINT = "Temple of Hands-Dried Paint"
    MUDFALLS = "Mudfalls"
    FACELESS_MOUNTAINS = "Faceless Mountains"
    MARAHS_ORCHARD = "Marah's Orchard"
    UNDERHEADS = "Underheads"
    KANKAN = "Kankan"
    JAGGED_FOREST = "Jagged Forest"
    BLADE_GARDEN = "Blade Garden"
    NAILGLADE = "Nailglade"
    TREE_ROOTS = "Tree Roots"
    DREGBOURG = "Dregbourg"
    PAINT_REEF = "Paint Reef"
    PALLADIUM = "Palladium"
    FALLEN_PATH = "Fallen Path"
    MUDPITS = "Mudpits"
    SKYRISE = "Skyrise"
    STARMIRE = "Starmire"
    WANTING_TREE = "Wanting Tree"
    POST_WANTING_TREE = "Post-Wanting Tree"

class LocTemple(StrEnum):
    """List of all Temple of Hands enums"""
    BIRTHPLACE_LOWER_MAUL_AXE = "ToH-Birthplace: Maul Axe"
    BIRTHPLACE_LOWER_ATRIUM_1 = "ToH-Birthplace: Atrium Left"
    BIRTHPLACE_LOWER_ATRIUM_2 = "ToH-Birthplace: Atrium Right"
    BIRTHPLACE_LOWER_OVERGROWN_BARRIER = "ToH: Overgrown Barrier"
    BIRTHPLACE_LOWER_LEFT = "ToH-Birthplace: Left of Surrogate"
    BIRTHPLACE_UPPER_FORMLESS_SKIN = "ToH-Birthplace: BIRTHPLACE_UPPER_FORMLESS_SKIN"
    BIRTHPLACE_UPPER_EMBEDDING_NAIL = "ToH-Birthplace: BIRTHPLACE_UPPER_EMBEDDING_NAIL"
    BIRTHPLACE_UPPER_FORCE_CAPACITY = "ToH-Birthplace: BIRTHPLACE_UPPER_FORCE_CAPACITY"
    DRIED_PAINT_HANDCLOTH_CHEST = "ToH-Dried Paint: Handcloth Chest"
    DRIED_PAINT_HANDCLOTH_HANDS = "ToH-Dried Paint: Handcloth Hands"
    DRIED_PAINT_KNIFEHAND = "ToH-Dried Paint: Knifehand"
    DRIED_PAINT_ATRIUM_SPIKE_PIT = "ToH-Dried Paint: Hidden Atrium in spike pit"
    DRIED_PAINT_HANDCLOTH_LEGS = "ToH-Dried Paint: Handcloth Legs"
    DRIED_PAINT_FRAGMENTS_BEFORE_SEAL = "ToH-Dried Paint: Fragments before Seal"
    DRIED_PAINT_ATRIUM_ABOVE_SEAL = "ToH-Dried Paint: Atrium above seal"
    DRIED_PAINT_FRAGMENTS_CHAINS_ROOM_1 = "ToH-Dried Paint: Fragments in Chains Room 1"
    DRIED_PAINT_FRAGMENTS_CHAINS_ROOM_2 = "ToH-Dried Paint: Fragments in Chains Room 2"
    DRIED_PAINT_CLASPED_MACE = "ToH-Dried Paint: Clasped Mace"
    DRIED_PAINT_ATRIUM_AFTER_CLASPED_MACE = "ToH-Dried Paint: Hidden Atrium after Clasped Mace"
    DRIED_PAINT_ITEM_SPIKE_PIT = "ToH-Dried Paint: Item in Spike Pit"
    HALL_SPIKE_GAP_FRAGMENTS = "ToH-Hall: Fragments past Spike Gap Above Surrogate"
    HALL_SPIKE_GAP_ATRIUM = "ToH-Hall: Atrium past Spike Gap Above Surrogate"
    SEALED_CHAMBER_FRAGMENTS = "ToH-Sealed Chamber: Fragments under Surrogate"
    SEALED_CHAMBER_BOUND_SHELL = "ToH-Sealed Chamber: Bound Shell drop"
    SEALED_CHAMBER_PRISMATIC_PEARL = "ToH-Sealed Chamber: Pearl above Surrogate"
    HALL_LEFT_OF_SURROGATE = "ToH-Hall: Left of Surrogate"
    HALL_RIGHT_OF_SURROGATE = "ToH-Hall: Right of Surrogate"
    HALL_EMBEDDING_NAIL_SURROGATE = "ToH-Hall: Ceiling item under Surrogate"
    HALL_THROWING_THUMBS = "ToH-Hall: Throwing Thumbs"
    HALL_ATRIUM_UNDER_YEARNING = "ToH-Hall: Ceiling item under Yearning Paint NPC"
    HALL_ATRIUM_ABOVE_SURROGATE = "ToH-Hall: Atrium above Surrogate"
    HALL_ATRIUM_TOPLEFT_SURROGATEL = "ToH-Hall: Atrium through gap above Surrogate"
    HALL_TOPLEFT_OVERGROWN_BLOB = "ToH-Hall: Overgrown Blob in top-left"
    HALL_TOPLEFT_ATRIUM = "ToH-Hall: Atrium in top-left"
    HALL_FRAGMENTS_ABOVE_SURROGATE = "ToH-Hall: Fragments on ledge above Surrogate"
    HALL_PEARL = "ToH-Hall: Pearl Above Hall"
    HALL_TOP_ATRIUM_BREAKABLE = "ToH-Hall: Ceiling Atrium near top"
    HALL_FRAGMENTS_AFTER_HUNT_ABOVE = "ToH-Hall: Fragments after Hunt Prey"
    HALL_FRAGMENTS_AFTER_HUNT_LEDGE = "ToH-Hall: Fragments after Hunt Prey on ledge"
    HALL_HOMING_DROPLET_TOP = "ToH-Hall: Item after Hunt Prey behind wall"
    HALL_RUST_FISTS = "ToH-Hall: Rust Fists"
